### ISSUE TITLE
Text fields as blobs in sqlite?

### ISSUE THREAD

**Issue by Grunthos** [dbmail/dbmail#105]
Search is not working properly with a fresh install using sqlite.

Blob fields in sqlite do not behave well with LIKE or GLOB, and the table ```dbmail_headervalue``` defined the ```headervalue``` field as a blob (I assume this is probably the case for other tables as well).

To see this in action, try:

```
create table foo(f blob);
insert into foo values('hello');
insert into foo values(cast('hello' as blob));
select typeof(f) from foo;
# text
# blob
select * from foo where f like 'hel%';
# hello
select * from foo where cast(f as text) like 'hel%';
#hello
#hello
```

The current db design *seems* to be incompatible with sqlite.

**Comment by CozC** [comment]
Salve,

I do no have much of an experience with sqlite, so I'll take your opinion  
for granted, but we, the users of DBMail would appreciate if you initiate  
a Pull Request with your changes, I'll review them if everything checks  
out  I'll accept it.

Have a nice day,

-- 
Cosmin Cioranu

**Comment by Grunthos** [comment]
Thanks for the quick response. 

Unfortunately there might have been good reasons for defining the field (and loading it) as a blob, and I do not know dbmail well enough to properly understand the ramifications of just changing it. Modifying the search is a possibility, but it's probably best to get whoever did the sqlite version to at least comment on the problem.

**Comment by CozC** [comment]
Salve ,

DBMail at its core is using libzdb which (with few exceptions) transforms  
it to a database agnostic system.

Fortunately the original developer gave DBMail to the community (and let  
few of us to have the right to integrate pull requests), unfortunately his  
answers regarding issues are a little hard to get, so it is up to us to  
make changes and fix the issues.

Having said that,
In your opinion some fields need to be changed in order to use the  
capabilities of sqlite, please offer a few pointers and if time lets me  
I'll make some tests and maybe some of your recommendation will make it to  
the next release.

Have a nice day,

-- 
Cosmin Cioranu

**Comment by Grunthos** [comment]
It may be sufficient to change the schema so the field is defined as text instead of blob, and create an appropriate upgrade step to rebuild 5he table, casting exiting values to text. Biy i have not had a chance to test this.

**Comment by CozC** [comment]
Thank you,

I will try those changes and see what happens.

Have a nice day.

On Fri, 18 Dec 2020 04:29:51 +0200, Grunthos <notifications@github.com>  
wrote:

>
> It may be sufficient to change the schema so the field is defined as  
> text instead of blob, and create an appropriate upgrade step to rebuild  
> 5he table, casting exiting values to >text. Biy i have not had a chance  
> to test this.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Using Opera's mail client: http://www.opera.com/mail/

**Comment by CozC** [comment]
The text field are all text, no blob, closing
