### ISSUE TITLE
SIGSEGV in imap_append_hash_as_string() at dm_misc.c

### ISSUE THREAD

**Issue by dfroehl** [dbmail/dbmail#12]
I noticed a crash of dbmail-imapd with core dump.

This seems to be caused by `strncpy` trying to copy `offset` (10570) bytes into `value` which has been allocated only 1024 bytes.

I tried to understand the code in `dm_misc.c`, `imap_append_hash_as_string()` to comprehend the situation under which this SIGSEGV occured in order to write a fix preventing this crash to happen again in the future.

I guess we should safe-guard the `strncpy` to avoid situations writing more than 1024 bytes into `value`. However I think this shouldn't ever happen. If I understand the backtrace right, the `head` pointer has exceeded the memory boundary of `type` which in turn shouldn't be possible in the `while(head)` loop for a null-terminated string.

Any ideas on this?
I am using dbmail 3.2.3 on FreeBSD 12.0.

```
(lldb) bt
* thread #1, name = 'dbmail-imapd', stop reason = signal SIGSEGV
    frame #0: 0x000000080097a6d5 libc.so.7`memset + 213
    frame #1: 0x0000000800962b52 libc.so.7`strncpy + 82
  * frame #2: 0x00000008002e55b6 libdbmail.so.0`imap_append_hash_as_string(list=0x0000000801ca3b60, type="attachment; filename=\"LZI_752802.pdf\";") at dm_misc.c:1417
(lldb) frame select 2
frame #2: 0x00000008002e55b6 libdbmail.so.0`imap_append_hash_as_string(list=0x0000000801ca3b60, type="attachment; filename=\"LZI_752802.pdf\";") at dm_misc.c:1417
   1414                         size_t len;
   1415                         char *clean1, *clean2, *clean3;
   1416                         memset(value, 0, sizeof(value));
-> 1417                         strncpy(value, head, offset);
   1418                         head += offset+1;
   1419                         inname = 1;
   1420                         offset = 0;
(lldb) frame variable
(GList *) list = 0x0000000801ca3b60
(const char *) type = 0x0000000803f5b690 "attachment; filename=\"LZI_752802.pdf\";"
(size_t) i = 12
(char) curr = '\0'
(char [512]) name = ""
(char [1024]) value = ""
(char *) head = 0x0000000803f5b6b6 ""
(GList *) l = 0x0000000801c189a0
(int) offset = 10570
(int) inname = 1
(size_t) len = 15
(char *) clean1 = 0x00007fffdf9fa3d1 ""
(char *) clean2 = 0x00000008036b6980 "LZI_752802.pdf"
(char *) clean3 = 0x00000008036d6240 "LZI_752802.pdf"
```

**Comment by CozC** [comment]
Well, I took a look over the issue and I must say it is interesting and it needs a patch. 
So the reason, in my opinion is related to glitch on the computing of value and it has to do with the state of the memory. 
In case of computing name there is not such a thing, due to 'continue' on 1412 but on value, things are very different. Indeed the offset is set to 0 and the head is set to position when it should reside the \0 char but the offset is incremented at 1449, so offset is always 1 after collecting value.
The test at 1401 will not work due to offset not being 0. 

Having said this, curr is collected after the ending of the string (\0) and here it comes the state of memory. If in that region of memory there is another buffer (like a valid string) then it goes...somewhere in your case increasing offset to weird values. 

So we will create an issue and we will create a patch. 
Thank you for taking the effort.

**Comment by CozC** [comment]
Issue has been fixed. Due to maintainers ways the merge on this trunk will be delayed. However the updates are up to date at https://github.com/CozC/dbmail

**Comment by awheeler** [comment]
It is possible this is the solution for: http://dbmail.org/mantis/view.php?id=1092, as it is fixing buffer overflow errors I've been seeing.
