### ISSUE TITLE
LMTP doesn't watch users.active

### ISSUE THREAD

**Issue by koniti** [dbmail/dbmail#122]
LMTP recieves all mail even if users.active=0.
attachment is quick hack patch for this, it works, but i'm not sure it's good for dbmail and i don't know better way.

[lmtp-active.diff.txt](https://github.com/dbmail/dbmail/files/6542846/lmtp-active.diff.txt)

**Comment by CozC** [comment]
Nice catch.

We will take a look into the matter.
Thank you also for the patch, it is nice to provide one. Also we would  
like to take a deeper look into the matter in order to understand the  
situation.

Thanks

On Wed, 26 May 2021 02:11:43 +0300, koniti ***@***.***>  
wrote:

>
> LMTP recieves all mail even if users.active=0.
> attachment is quick hack patch for this, it works, but i'm not sure it's  
> good for dbmail and not know beter way.
>
> lmtp-active.diff.txt
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by cncioranu** [comment]
I took a look over your fix, it will work on aliases, but the `delivered_to` is used, also, in forwarding also. Although it works in your case it needs a little bit of work to support the forwarding (external).
Nice work in tracing the code up 'till this point, I will use it and add the necessary changes to support the external forwarding. 
Thanks.
