### ISSUE TITLE
Portability fix on Solaris

### ISSUE THREAD

**Issue by fazalmajid** [dbmail/dbmail#124]
In addition to the fixes in #123, I had to remove `#include <features.h>` from dbmail.h.in to get it to build on SmartOS (Illumos/Solaris derived).

**Comment by cncioranu** [comment]
I have checked the configuration, `features.h` is loaded only if the platform is other then FREEBSB, APPLE and SANPRO_C, can you please tell me if SmartOS has a generic constant declared in order to use them in 
`
#if defined(__FreeBSD__) || defined(__APPLE__) || defined(__SUNPRO_C)

#define _XOPEN_SOURCE

#else

#define _XOPEN_SOURCE	500
#include <features.h>

#endif
`
Thank you.

**Comment by cncioranu** [comment]
I have found some references related to `defined(__SMARTOS__) || defined(__ILLUMOS__)` is this correct?

**Comment by fazalmajid** [comment]
I no longer have an (Oracle) Solaris machine or VM handy, but I would assume the same issues occur there as well and would suggest using:

```
  #if defined(__FreeBSD__) || defined(__APPLE__) || defined(__SUNPRO_C) || defined(__sun)
  
  #define _XOPEN_SOURCE
  
  #else
  
  #define _XOPEN_SOURCE	500
  #include <features.h>
  
  #endif
```

The Illumos or SmartOS macros should only be used where Illumos has diverged from Solaris, and that's not all that frequent (mostly the adoption of Linux APIs like inotify).

Thanks!

**Comment by CozC** [comment]
Thank you. Added in the latest PR.

**Comment by CozC** [comment]
closing.
