### ISSUE TITLE
Duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by BobRam** [dbmail/dbmail#134]
dbmail 3.2.5 built from sources:

postgres        | 2021-12-07 22:31:30.661 MSK [39] ERROR:  duplicate key value violates unique constraint "dbmail_header_pkey"
postgres        | 2021-12-07 22:31:30.661 MSK [39] DETAIL:  Key (physmessage_id, headername_id, headervalue_id)=(289, 1, 534) already exists.
postgres        | 2021-12-07 22:31:30.661 MSK [39] STATEMENT:  INSERT INTO dbmail_header (physmessage_id, headername_id, headervalue_id) VALUES ($1,$2,$3)
postgres        | 2021-12-07 22:31:30.662 MSK [39] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres        | 2021-12-07 22:31:30.662 MSK [39] STATEMENT:  SET statement_timeout TO 3000;
postgres        | 2021-12-07 22:31:30.662 MSK [39] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres        | 2021-12-07 22:31:30.662 MSK [39] STATEMENT:  DEALLOCATE "26";
postgres        | 2021-12-08 00:10:51.809 MSK [438] LOG:  could not send data to client: Connection reset by peer
postgres        | 2021-12-08 00:10:51.809 MSK [438] FATAL:  connection to client lost

**Comment by cncioranu** [comment]
Hello, I searched a little bit, and it happens when there is a duplicate header in the delivered email. The code is specially designed to rollback the second (or more) duplicate header so it should not have caused issues at the app level. 
My test were made on mysql/mariadb backend but it did not caused any issues (a rollback).
However, those transaction (and implicit rollback) is handled by libzdb so my guess is that it might have something to do with the exception thrown. Withoud the actual headers of the original message debugging is quite hard. 
As an imediate workaround is to disable de primary key (in order to avoid the conflict) or check if you can rebuild the dbmail using another version of libzdb. 

We are still investigate the issue.

**Comment by CozC** [comment]
closing,
