### ISSUE TITLE
Where is mail content stored? _mailboxes, _message - has no mail content?

### ISSUE THREAD

**Issue by StarMonk** [dbmail/dbmail#17]
Where is mail content stored? dbmail_mailboxes, dbmail_message - has no mail content?

And has everything. Only `dbmail_mimeparts` has raw data of all mail inside `data` column.

Where to fetch "mail content" just like "dbmail_subjectfield" has subject of mail. Where is "mail content" stored?

**Comment by StarMonk** [comment]
@langemeijer , @pjstevns , @CozC @alan-hicks 

any tips?

**Comment by CozC** [comment]
Salve, 

The way mails are stored in the db are quite fragmentated due to the need of optimization. 
Mails are stored in dbmail_messages, and here you may find, among other things, the mailbox reference, flags (etc.) and one crucial piece of information physical message id. 
Having this in mind, the physical message are stored in dbmail_physmessages and the contents of the message is stored using references found in dbmail_partlist,dbmail_mimeparts, dbmail_header, dbmail_headervalue. 
So, in dbmail_messages are stored all messages received by your users/mailboxes and in physical messages you can find all messages that were delivered to the server (eg: if you send an email 2 recipients of this server you may have 2 entries in dbmail_messages and one entry in dbmail_physmessages)
Bellow you may find and example of queries that retrieves some information:

#Retrieve some information about a message, replace xxxx with an id from dbmail_messages
 

	select 
		m.message_idnr messageId,
		m.physmessage_id AS physicalMessageId,
		ph.internal_date AS internal_date,
		max(if(n.headername = 'from',v.headervalue,NULL)) AS sendFrom,
		max(if(n.headername = 'to',v.headervalue,NULL)) AS sentTo,
		max(if(n.headername = 'subject',v.headervalue,NULL)) AS Subject
	from 
		((((dbmail_messages m join dbmail_header h on(m.physmessage_id = h.physmessage_id))
			join dbmail_physmessage ph on(m.physmessage_id = ph.id))
			join dbmail_headername n on(h.headername_id = n.id))
			join dbmail_headervalue v on(h.headervalue_id = v.id))
	where
		(n.headername = 'to' or n.headername = 'from' or n.headername = 'subject' )
			and m.message_idnr=xxxxxx
	group by m.physmessage_id

#Retrieve the mail parts of a message, replace xxxx with an id from dbmail_messages

	
	select
		m.message_idnr 'messageId',
		list.physmessage_id AS 'physicalMessageId',
		prts.id as 'PartId',
		cast(prts.data as varchar(8192)) d,
		list.is_header
	from
		dbmail_messages m,
		dbmail_mimeparts prts,	
		dbmail_partlists list
	where
	 
	list.part_id = prts.id
	and m.physmessage_id=list.physmessage_id
	and 	m.message_idnr=xxxxx


Hope this helps.

**Comment by StarMonk** [comment]
Thanks! that was very helpful.

**Comment by StarMonk** [comment]
I must agree, these database schema are not at all scalable - Fetching "mail" for particular email address with required data consits of 10 tables. This is seriously flawed. 

Want to send PR, but it's too much work to change most of the thing.

I say this because I have some of my application serving million request each page with 150+ total web pages and I have to use single table data for each information without foreign key or join thing.

**Comment by CozC** [comment]
I'm not quite in agreement with you. I would argue that the current state of implementation is adequate in your use case and is quite scalable using various methods of Master-Master/Master-Slave configurations (see galera or master/slave mysql support). Considering your millions of accesses you would use dbmail_messagess as a selector of message because it does have all needed references and then request additional information if it is required using various methods and queries to solve your needs. 
Considering your other statements I suppose you would expect all messages be stored in one place. That should be considered poor implementation due to the nature of an email (an email have headers and the message body is broken into various parts, which do have various encoding)
I do admit dbmail is not entirely developed in terms of tools and ways to manipulate data but that is left to you( tailor your own solution as you please, and use dbmail to receive and administrate messages using various daemons).

**Comment by CozC** [comment]
Not quite an issue. More can be found by joining mailing list at [https://www.dbmail.org/index.php?page=mailinglists](here)
