### ISSUE TITLE
Can't create table dbmail_auto_replies

### ISSUE THREAD

**Issue by ajdelgado** [dbmail/dbmail#173]
When creating the MySQL tables using /usr/src/dbmail-3.3.0/sql/mysql/create_tables.mysql, I get the error:
Can't create table `dbmail`.`dbmail_auto_replies` (errno: 121 "Duplicate key on write or update")

**Comment by CozC** [comment]
Salve,

It is due to a duplicate FK name... unfortunately, now, mysql does check  
also this information, in older versions this behavior was permitted.
Fast change until we recheck everything is to change the name of the  
foreign key name
`
DROP TABLE IF EXISTS dbmail_auto_replies;
CREATE TABLE dbmail_auto_replies (
user_idnr bigint(20) UNSIGNED DEFAULT '0' NOT NULL,
start_date DATETIME NOT NULL,
stop_date DATETIME NOT NULL,
reply_body MEDIUMTEXT,
INDEX user_idnr_index (user_idnr),
FOREIGN KEY ar_user_idnr_fk (user_idnr)
REFERENCES dbmail_users (user_idnr) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB DEFAULT CHARSET=utf8;
`

I did change `user_idnr_fk` into `ar_user_idnr_fk`. Do the same if other  
similar issues you may find

Hope it helps.

-- 
CC @gmail

**Comment by alan-hicks** [comment]
Pull request #174 created to fix this issue.

**Comment by alan-hicks** [comment]
Fixed with pull request #174
