### ISSUE TITLE
memory-leak dbmail-lmtpd

### ISSUE THREAD

**Issue by le-kazankin** [dbmail/dbmail#186]
Hello, i have a problem with memory-leak of dbmail-lmtpd.

It appers on load of 4.6k messages per day.
How to fix it?

My env:
1. Centos 7.7
2. DBmail 3.3.1
3. MTA: Exim 4.94.2

![dbmail_htop](https://user-images.githubusercontent.com/88597608/232658253-e739bc8c-79d2-4f94-b887-2aa420d2d20f.png)
![memory_graph](https://user-images.githubusercontent.com/88597608/232658263-d57af884-c1fb-4baa-8a0b-051a0300a7db.png)

**Comment by alan-hicks** [comment]
Thanks for this report, and apologies for late reply, I've been off-grid for a few days.

Most of the dbmail memory leaks are from the over forty dependencies rather than dbmail as Paul and myself have spent a lot of time investigating and fixing them. It's an ongoing effort.

With 4.6k messages per day it may be better to manage memory usage until all these memory leaks are fixed. Nagios and similar tools have check_procs to monitor memory and restart services.

The following link may help
https://dbmail.org/docs/managing-memory/

**Comment by alan-hicks** [comment]
Closing this issue as memory issues appear to be from libraries and there are workarounds to mitigate excessive memory usage.
