### ISSUE TITLE
How to add new additional domain as well as domain alias to server for dbmail compatible?

### ISSUE THREAD

**Issue by StarMonk** [dbmail/dbmail#19]
I have one base domain working perfectly with dbmail, But I have 2 additional domain - I want to use in same dbmail server. 

Is there any way to add additional domain and create email based on new additional domain with dbmail?

Thanks

**Comment by CozC** [comment]
Salve,

By domain do you mean you 3 separate domains (names) on the same server or  
you have 3 servers (diffrent IPs), each serving an individual domain?

No matter the situation the answer is yes, but the issue is not related to  
dbmail but with your MTA (eg: postfix) . In case of 3 servers, the  
configuration will be more complicated but still doable.



On Tue, 31 Dec 2019 11:40:38 +0200, Star Monk <notifications@github.com>  
wrote:

>
> I have one base domain working perfectly with dbmail, But I have 2  
> additional domain - I want to use in same dbmail server.
>
> Is there any way to add additional domain and create email based on new  
> additional domain with dbmail?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Not really an issue is more help and assistance. 
More can be found by joining the mailing lists. [https://www.dbmail.org/index.php?page=mailinglists](here)
