### ISSUE TITLE
dbmail generates a possibly invalid BODYSTRUCTURE, that java clients don't like

### ISSUE THREAD

**Issue by awheeler** [dbmail/dbmail#23]
When the content-type header is not present in an email, dbmail generates a possibly incomplete BODYSTRUCTURE:
`BODYSTRUCTURE ("text" "plain" NIL NIL "7BIT" 4669 2294 NIL NIL NIL NIL)`
Rather than:
`BODYSTRUCTURE ("text" "plain" NIL NIL NIL "7BIT" 4669 2294 NIL NIL NIL NIL)`

Non java clients seem to be fine with this, but java clients barf, sometimes quietly.

Looking through the code, I believe this difference is unintended.

It seems to be due to a call in `dm_misc.c` to:
`imap_append_hash_as_string(GList *list, const char *type)`
Where type is null, which happens when a call to:
`g_mime_object_get_header(object, "Content-Type")`
returns a null for the Content-Type, ie, when there is no Content-Type header.

The code in imap_append_hash_as_string returns an unmodified list when the passed-in type is `null`, where I believe it should append a `'NIL'` and return the list.

I will submit a merge request with this implemented shortly, and the change does fix the issue in my environment.

**Comment by CozC** [comment]
Salve, 
Only for the documentation purposes: 
The [RFC3501 ](https://tools.ietf.org/html/rfc3501#page-12) is a little bit fuzzy in regards of missing data structure. In this case it will qualify `NIL` but also `()`, so taking into consideration this, the patch should be accepted

Can you please give more info related to the version of DBMail, possibly the linux distribution and (maybe) java package, just for documentation sake and in order to if we back porting it to a older version?

**Comment by CozC** [comment]
Changes added

**Comment by awheeler** [comment]
Sure
dbmail: release 3.2.3 with some patches
Linux: CentOS 6.10

Client data:
Linux: CentOS 7.7
Java: OpenJDK 1.8.0_242
Java library: com.sun.mail.iap
Java error: ParsingException, as documented [here](http://edelstein.pebbles.cs.cmu.edu/jadeite/main.php?api=javamail&state=class&package=com.sun.mail.iap&class=ParsingException)

**Comment by CozC** [comment]
Thank you,

Your commit was pushed in the active development.
Thank you again.

May I ask about your patches? I also have some added into my own  
production environments, and all were pushed into active development (all  
most all), among them:
- issue related to a buffer overflow (in the same method you have made  
modifications) #22
- issue related to fd leaks (#13)
- issue related to MODIFIED keyword
- issue related * OK Still here
- and some others (almost all found on issues or pull request section)

Thank you.

On Thu, 02 Apr 2020 19:17:06 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> Sure
> dbmail: release 3.2.3 with some patches
> Linux: CentOS 6.10
>
> Client data:
> Linux: CentOS 7.7
> Java: OpenJDK 1.8.0_242
> Java library: com.sun.mail.iap
> Java error: ParsingException, as documented here
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment]
You're welcome, and thank you!  I'm super happy to see activity here, as I was beginning to think dbmail had become abandonware.  I've been thinking about moving dbmail into docker too, only wondering about persistent storage of the email receipt side of things.
I actually just found and patched the same buffer overflow you did, before I noticed you had an unmerged (to this repo) fix.  I like yours better, so going to switch to it :)
This is roughly my patches: [here](https://github.com/awheeler/dbmail/commits/dbmail_3_2_eab)
I say roughly as I'm moving to that set from a bunch of patch files that are a little different.
I also have an internal patch to move messages rather than copy them (internal business requirement).  I know this breaks IMAP, so def won't offer that patch here unless someone wanted it.

**Comment by CozC** [comment]
Thank you for the link repository, very useful.

I will take a closer look to all of them. As you have said some of them  
are already included in the main trunk and some are not (especially those  
related to stability, FD leaks)

Next on my table,
- I  have seen some slowness in some queries, and I have some patches to  
be pushed in near future (some in sql schema, related to indexes and some  
at the code level)
- improvements, and more improvements hopefully from the ones are using it.
- maybe a new release, if Paul does allow it under the name of DBMail or  
some other variation (under the same copyright), I do not hold any control  
over dbmail.org so it cannot be pushed there (the tar.gz)
- if would like to release dbmail in rpm form, also  if Paul allows for  
DBMail to be used as name or other variation of my own devise.

Also, I like too much the DBMail idea, giving the fact that I use galera  
cluster and it offers great flexibility in terms of processes.

As a final note: from the time being I will try to keep up with fixing and  
offering patches.

Have a nice day.


On Thu, 02 Apr 2020 21:49:12 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> You're welcome, and thank you! I'm super happy to see activity here, as  
> I was beginning to think dbmail had become abandonware. I've been  
> >thinking about moving dbmail into docker too, only wondering about  
> persistent storage of the email receipt side of things.
> I actually just found and patched the same buffer overflow you did,  
> before I noticed you had an unmerged (to this repo) fix. I like yours  
> better, so >going to switch to it :)
> This is roughly my patches: here
> I say roughly as I'm moving to that set from a bunch of patch files that  
> are a little different.
> I also have an internal patch to move messages rather than copy them  
> (internal business requirement). I know this breaks IMAP, so def won't  
> offer >that patch here unless someone wanted it.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
@awheeler

As mentioned in a previous post, I pushed into a branch (  
https://github.com/nbeta-git/dbmail/tree/optimization_aquire-msg-headers )  
some updates I already use in production environment. I'm still evaluating  
if some how breaks RFC (I have mixed feelings about them, due to the  
duality of a message in DBMail (deleted_flag and status), in terms of RFC,  
but nevertheless they are improving overall performances of the entire  
production servers)

So, first it limits the access to deleted messages ( I mean deleted  
messages decided by DBMail not messages marked as deleted via flags).  
DBMail on each succesuful connection (and selection of folder), it creates  
a state of that folder. That state will grow even if user somehow keeps it  
tidy and clean (even on POP, dbmail creates that state of poped messages,  
now deleted). Why there are issues here, because those messages are  
deleted (status=2) and cannot have their status changed anyway.
2nd, I notice that when creating that state, there are 2 queries, one is  
collecting messages (and states, sizes etc.) and the other is collecing  
keywords. In large folders those 2 processes can take longer so they were  
merge in one query.
3rd, I pushed also an optimization when messages are queried via  
bodystructure. Queries are quite slow when used in constructions like  
'headername in ('h1','h2'...) so that also changed and added the earlier  
limitations.
Hope it can be useful




On Fri, 03 Apr 2020 07:45:25 +0300, Cosmin CIORANU  
<cosmin.cioranu@gmail.com> wrote:

> Thank you for the link repository, very useful.
> I will take a closer look to all of them. As you have said some of them  
> are already included in the main trunk and some are not (especially  
> those >related to stability, FD leaks)
>
> Next on my table,- I  have seen some slowness in some queries, and I  
> have some patches to be pushed in near future (some in sql schema,  
> related to indexes >and some at the code level)
> - improvements, and more improvements hopefully from the ones are using  
> it. - maybe a new release, if Paul does allow it under the name of  
> DBMail or some other variation (under the same copyright), I do not hold  
> any control >over dbmail.org so it cannot be pushed there (the tar.gz)
> - if would like to release dbmail in rpm form, also  if Paul allows for  
> DBMail to be used as name or other variation of my own devise.
> Also, I like too much the DBMail idea, giving the fact that I use galera  
> cluster and it offers great flexibility in terms of processes.
>
> As a final note: from the time being I will try to keep up with fixing  
> and offering patches.
> Have a nice day.
>
> On Thu, 02 Apr 2020 21:49:12 +0300, Alex Wheeler  
> <notifications@github.com> wrote:
>
>>
>> You're welcome, and thank you! I'm super happy to see activity here, as  
>> I was beginning to think dbmail had become abandonware. I've been  
>> >>thinking about moving dbmail into docker too, only wondering about  
>> persistent storage of the email receipt side of things.
>> I actually just found and patched the same buffer overflow you did,  
>> before I noticed you had an unmerged (to this repo) fix. I like yours  
>> better, so >>going to switch to it :)
>> This is roughly my patches: here
>> I say roughly as I'm moving to that set from a bunch of patch files  
>> that are a little different.
>> I also have an internal patch to move messages rather than copy them  
>> (internal business requirement). I know this breaks IMAP, so def won't  
>> >>offer that patch here unless someone wanted it.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>
>
>
> --Cosmin Cioranu



-- 
Cosmin Cioranu

**Comment by awheeler** [comment]
Oh, nice!  I think that could be helpful indeed, I had no idea it was creating and maintaining an ever growing state .
So are you taking over for Paul in managing dbmail?
Also, I have a new issue with the same java client and the BODYSTRUCTURE returned by dbmail, but I'm still trying to figure out what's going on.
I'll open a new ticket for that, unless you'd like to just re-open this one.

**Comment by CozC** [comment]
Salve,

Yes we (Paul, me and others) are in the same boat in this. Hopefully he  
will have some spear time for this.

Regarding  the  BODYSTRUCTURE issue, it's related to the old one or it is  
a new issue? I have no issue in reopening, but I feel it should be open a  
new one. If we mix 2 issues (even they feel the same) we may find ourself  
in the position of not understanding what and why some choices were made  
(so open a new one and link this issue to the older one, in order to keep  
it tidy)

I gave some thought about the patch I was talking and I'm confident RFC is  
not broken, but this talk should be held on a thread all by itself.

Have a nice evening.


On Mon, 06 Apr 2020 21:24:58 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> Oh, nice! I think that could be helpful indeed, I had no idea it was  
> creating and maintaining an ever growing state .
> So are you taking over for Paul in managing dbmail?
> Also, I have a new issue with the same java client and the BODYSTRUCTURE  
> returned by dbmail, but I'm still trying to figure out what's going on.
> I'll open a new ticket for that, unless you'd like to just re-open this  
> one.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment]
Good point, It's a new issue, so I'll open a new ticket.  Glad to hear the change won't break RFC
