### ISSUE TITLE
RPM Building issue: 64bit-portability-issue

### ISSUE THREAD

**Issue by bajizs** [dbmail/dbmail#61]
When build RPM on Suse Build Service I get this problem on packing:

64bit-portability-issue dm_imapsession.c:1609
64bit-portability-issue dm_misc.c:87

**Comment by bajizs** [comment]
Ok, problem is in declaration.

I have added to file dm_mailboxstate.h line:
extern T            MailboxState_update(Mempool_T pool, T OldM);

But I dont known who to solve for backtrace_symbols... Not found in other files definition

**Comment by CozC** [comment]
Nice catch.

You are correct. In the differential state update that declaration was  
missing. It will be added.

Thank you.
Regarding the backtrace symbols you may try to use the following flags  
(I'll send the whole ./configure parameters in order to be clear). Those  
parameters are ok if you will use valgrind or gdb.

./configure --prefix=[path] --sysconfdir=[path] --with-sieve=[path]  
--with-zdb=[path] CFLAGS="-g -g3 -gdwarf-2" CXXFLAGS="-g -g3 -gdwarf-2"

Also if you would like to run tests add `--with-check` and then run `make  
check`

Hope it helps.


On Thu, 14 May 2020 21:45:34 +0300, Baji Zsolt <notifications@github.com>  
wrote:

>
> Ok, problem is in declaration.
>
> I have added to file dm_mailboxstate.h line:
> extern T MailboxState_update(Mempool_T pool, T OldM);
>
> But I dont known who to solve for backtrace_symbols... Not found in  
> other files definition
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
fixed
