### ISSUE TITLE
BSD systems don't use proc

### ISSUE THREAD

**Issue by alan-hicks** [dbmail/dbmail#74]
get_opened_fd_count should return zero on FreeBSD type systems

There was an ifdef to do this:
https://github.com/pjstevns/dbmail/pull/46/files#diff-c6a39d85434c5cd409eac50923f2ac1e

int get_opened_fd_count(void)
{
#if defined(__FreeBSD__) || defined(__APPLE__) || defined(__SUNPRO_C)
	// BSD like systems don't use proc
	return 0;
#else
	DIR* dir = NULL;
	struct dirent* entry = NULL;
	char buf[32];
	closedir(dir);
	return fd_count - 2; /* exclude '.' and '..' entries */
#endif
}

**Comment by CozC** [comment]
It seems that the ifdef were lost... I'll add those as soon as I find some  
time.
Thank you for the research.





On Fri, 26 Jun 2020 14:59:36 +0300, Alan Hicks <notifications@github.com>  
wrote:

>
> get_opened_fd_count should return zero on FreeBSD type systems
>
> There was an ifdef to do this:
> https://github.com/pjstevns/dbmail/pull/46/files#diff-c6a39d85434c5cd409eac50923f2ac1e
>
> int get_opened_fd_count(void)
> {
> #if defined(FreeBSD) || defined(APPLE) || defined(__SUNPRO_C)
> // BSD like systems don't use proc
> return 0;
> #else
> DIR* dir = NULL;
> struct dirent* entry = NULL;
> char buf[32];
> closedir(dir);
> return fd_count - 2; /* exclude '.' and '..' entries */
> #endif
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Pushed changes. Pleas review them before merging, if you have some time. ------ Original message------From: Cosmin CIORANUDate: Fri, Jun 26, 2020 20:51To: dbmail/dbmail;Alan Hicks;dbmail/dbmail;Cc: Subscribed;cosmin.cioranu@gmail.com;Subject:Re: [dbmail/dbmail] BSD systems don't use proc (#74)It seems that the ifdef were lost... I'll add those as soon as I find some time. Thank you for the research. On Fri, 26 Jun 2020 14:59:36 +0300, Alan Hicks > wrote:
get_opened_fd_count should return zero on FreeBSD type systems
There was an ifdef to do this:
https://github.com/pjstevns/dbmail/pull/46/files#diff-c6a39d85434c5cd409eac50923f2ac1e
int get_opened_fd_count(void)
{
#if defined(FreeBSD) || defined(APPLE) || defined(__SUNPRO_C)
// BSD like systems don't use proc
return 0;
#else
DIR* dir = NULL;
struct dirent* entry = NULL;
char buf[32];
closedir(dir);
return fd_count - 2; /* exclude '.' and '..' entries */
#endif
}

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Cosmin Cioranu

**Comment by CozC** [comment]
Fixed
